fix typescript build issues after upgrading to typescript@1.8.10 remove colors and use chalk instead - colors add on top of String which causes problems in ES6. install core-js to fix error TS2304: Cannot find name 'IterableIterator'